switch from Reflection Library to ClassGraph
SHOW STOPPER
Reflections Library works fine for development and run in Eclipse,
but it turns out not to be thread safe and scanning the Spring jar
throws
ERROR org.jeets.dcs.traccar.ServerManager
- Traccar Server setup failed: zip file closed
  java.lang.IllegalStateException: zip file closed